import { type BalanceMap } from "@compilot/merkle-tree-js";

// this is the list generated by the contract project
import allowListObj from "./allowListObj.json";

export const CUSTOMERS_BALANCE_MAP: BalanceMap[] = allowListObj.balances;
